server:
  port: 8080

spring:
  application:
    name: library
  profiles:
    active: @env@
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: true


logging:
  path: ./log
  config: classpath:logback-spring.xml
  file:
    max-history: 100


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: FULL
    auto-mapping-unknown-column-behavior: FAILING


rest:
  readTimeout: 30000
  connectTimeout: 30000

