spring:
  datasource:
    url: jdbc:mysql://aeonbanklibrary.c9qm6semu9r3.ap-southeast-1.rds.amazonaws.com:3306/aeonbanklibrary
    username: cyrus
    password: Cyrus12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


logging:
  path: /myapp/log
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
    com:
      aeonbank:
        library:
          controller: DEBUG
          repository: DEBUG
          service: DEBUG

