spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aeonbanklibrary
    username: cyrus
    password: cyrus
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
    com:
      aeonbank:
        library:
          controller: DEBUG
          repository: DEBUG
          service: DEBUG

