spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aeonbanklibrary
    username: cyrus
    password: cyrus
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      host: 172.20.18.39
      port: 27017
      database: aeonbanklibrary
      #username:
      #password:
  redis:
    database: 0
    host: 172.20.18.39
    port: 6379
    #password:
  rabbitmq:
    addresses: amqp://172.20.18.39:5672
    virtual-host: aeonbanklibrary
    username: cyrus
    password: cyrus


logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
    com:
      aeonbank:
        library:
          controller: DEBUG
          repository: DEBUG
          service: DEBUG

